[package]
name = "fuse_ast"
version = "0.1.0"
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
paste = { workspace = true }
serde = { workspace = true }
