[package]
name = "fuse_visitor"
version = "0.0.0"
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
fuse_ast = { workspace = true }
