name: Test
on:
  # push:
  #   branches:
  #     - master


  workflow_dispatch:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log
        run: |
          ls -la
          cd crates
          ls -la
          cd fuse-parser
          ls -la
          cd tests
          ls -la

      - name: Test
        run: cargo test --verbose
